### ISSUE TITLE
Template Support

### ISSUE THREAD

**Issue by seantimm** [alexblunck/html-webpack-plugin-remove#1]
Hi Alex,

You may be doing this for learning reasons of your own, but I wanted to make sure you were aware that the html-webpack-plugin supports custom templates, so you can just give it the exact markup you prefer:
https://github.com/ampedandwired/html-webpack-plugin#writing-your-own-templates

-Sean

**Comment by alexblunck** [comment]
Hi Sean,

the reason I made this was to exclude the style.js file, generated by the [extract-text-webpack-plugin](https://github.com/webpack/extract-text-webpack-plugin) plugin for some reason, since it serves absolutely no function. 

I simply wanted to prevent an extra / unnecessary http request.

It looks like I'm not the only one with this issue: [issue](https://github.com/webpack/extract-text-webpack-plugin/issues/175). 

Greetings,
Alex
